# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
### [your code here]
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [19]:
### [your code here]
print(np.version.version)

1.26.4


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [72]:
### [your code here]
a = np.random.rand(2, 3, 5)



### 4. Print a.


In [22]:
### [your code here]
print(a)

[[[0.02142715 0.22847828 0.23636085 0.27372269 0.87363296]
  [0.75970565 0.62323311 0.84938767 0.03884973 0.91106535]
  [0.40066535 0.00599448 0.09307211 0.980551   0.8526186 ]]

 [[0.93485536 0.96221093 0.62466333 0.88549352 0.85552566]
  [0.67488414 0.84479562 0.03385445 0.18954918 0.51914385]
  [0.14453054 0.84071941 0.40506194 0.2662533  0.9971622 ]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [23]:
### [your code here]
b = np.ones((5,2,3))



### 6. Print b.


In [24]:
### [your code here]
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [25]:
### [your code here]
print(a.size == b.size)

True



### 8. Are you able to add a and b? Why or why not?


In [27]:
### [your code here]
"""Yes, you can. But you have to keep some things in mind:
They must have the same dimensions or shape of the matrices. Not 1D and 3D arrays, for example.
However, you can concatenate them, which is not arithmetic addition, they're just following each other."""

"Yes, you can. But you have to keep some things in mind:\nThey must have the same dimensions or shape of the matrices. Not 1D and 3D arrays, for example.\nHowever, you can concatenate them, which is not arithmetic addition, they're just following each other."



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [49]:
### [your code here]
print(a)
c = np.transpose(b,(1,2,0))
print(c)

[[[0.02142715 0.22847828 0.23636085 0.27372269 0.87363296]
  [0.75970565 0.62323311 0.84938767 0.03884973 0.91106535]
  [0.40066535 0.00599448 0.09307211 0.980551   0.8526186 ]]

 [[0.93485536 0.96221093 0.62466333 0.88549352 0.85552566]
  [0.67488414 0.84479562 0.03385445 0.18954918 0.51914385]
  [0.14453054 0.84071941 0.40506194 0.2662533  0.9971622 ]]]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [50]:
### [your code here]
d = a+c
print(d)

"""They have the same shape, so every part of the array has a correspondant in the other array, which it's mandatory for adding two arrays."""

[[[1.02142715 1.22847828 1.23636085 1.27372269 1.87363296]
  [1.75970565 1.62323311 1.84938767 1.03884973 1.91106535]
  [1.40066535 1.00599448 1.09307211 1.980551   1.8526186 ]]

 [[1.93485536 1.96221093 1.62466333 1.88549352 1.85552566]
  [1.67488414 1.84479562 1.03385445 1.18954918 1.51914385]
  [1.14453054 1.84071941 1.40506194 1.2662533  1.9971622 ]]]


"They have the same shape, so every part of the array has a correspondant in the other array, which it's mandatory for adding two arrays."


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [51]:
### [your code here]
print(a)
print(d)
"""It's an addition of c with a value of 1 and a. Every part of the array finds its correspondant at the same place."""

[[[0.02142715 0.22847828 0.23636085 0.27372269 0.87363296]
  [0.75970565 0.62323311 0.84938767 0.03884973 0.91106535]
  [0.40066535 0.00599448 0.09307211 0.980551   0.8526186 ]]

 [[0.93485536 0.96221093 0.62466333 0.88549352 0.85552566]
  [0.67488414 0.84479562 0.03385445 0.18954918 0.51914385]
  [0.14453054 0.84071941 0.40506194 0.2662533  0.9971622 ]]]
[[[1.02142715 1.22847828 1.23636085 1.27372269 1.87363296]
  [1.75970565 1.62323311 1.84938767 1.03884973 1.91106535]
  [1.40066535 1.00599448 1.09307211 1.980551   1.8526186 ]]

 [[1.93485536 1.96221093 1.62466333 1.88549352 1.85552566]
  [1.67488414 1.84479562 1.03385445 1.18954918 1.51914385]
  [1.14453054 1.84071941 1.40506194 1.2662533  1.9971622 ]]]


"It's an addition of c with a value of 1 and a. Every part of the array finds its correspondant at the same place."


### 12. Multiply a and c. Assign the result to e.


In [52]:
### [your code here]
e = a * c
print(e)

[[[0.02142715 0.22847828 0.23636085 0.27372269 0.87363296]
  [0.75970565 0.62323311 0.84938767 0.03884973 0.91106535]
  [0.40066535 0.00599448 0.09307211 0.980551   0.8526186 ]]

 [[0.93485536 0.96221093 0.62466333 0.88549352 0.85552566]
  [0.67488414 0.84479562 0.03385445 0.18954918 0.51914385]
  [0.14453054 0.84071941 0.40506194 0.2662533  0.9971622 ]]]




### 13. Does e equal to a? Why or why not?


In [53]:
### [your code here]
print(a)
print("-------------")
print(e)
"""Yes, it's the same because c is an array of 1, so x*1=1"""


[[[0.02142715 0.22847828 0.23636085 0.27372269 0.87363296]
  [0.75970565 0.62323311 0.84938767 0.03884973 0.91106535]
  [0.40066535 0.00599448 0.09307211 0.980551   0.8526186 ]]

 [[0.93485536 0.96221093 0.62466333 0.88549352 0.85552566]
  [0.67488414 0.84479562 0.03385445 0.18954918 0.51914385]
  [0.14453054 0.84071941 0.40506194 0.2662533  0.9971622 ]]]
-------------
[[[0.02142715 0.22847828 0.23636085 0.27372269 0.87363296]
  [0.75970565 0.62323311 0.84938767 0.03884973 0.91106535]
  [0.40066535 0.00599448 0.09307211 0.980551   0.8526186 ]]

 [[0.93485536 0.96221093 0.62466333 0.88549352 0.85552566]
  [0.67488414 0.84479562 0.03385445 0.18954918 0.51914385]
  [0.14453054 0.84071941 0.40506194 0.2662533  0.9971622 ]]]


"Yes, it's the same because c is an array of 1, so x*1=1"



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [54]:
### [your code here]

d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [66]:
### [your code here]
f = np.empty(d.shape)
print(f)

[[[0.02142715 0.22847828 0.23636085 0.27372269 0.87363296]
  [0.75970565 0.62323311 0.84938767 0.03884973 0.91106535]
  [0.40066535 0.00599448 0.09307211 0.980551   0.8526186 ]]

 [[0.93485536 0.96221093 0.62466333 0.88549352 0.85552566]
  [0.67488414 0.84479562 0.03385445 0.18954918 0.51914385]
  [0.14453054 0.84071941 0.40506194 0.2662533  0.9971622 ]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [ ]:
### [your code here]

condition = (d == d_max)
f[condition] = 100
condition = (d == d_min)
f[condition] = 0
condition = (d > d_min) & (d < d_mean)
f[condition] = 25
condition = (d > d_mean) & (d < d_max)
f[condition] = 75
condition = (d == d_mean)
f[condition] = 50

print(f)
print(d_max)
print(d_min)

"""Method 2
f = np.where((d > d_min) & (d < d_mean), 25, f)

Method 3
f = np.empty(d.shape)
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d_min < d[i, j, k] < d_mean:
                f[i, j, k] = 25
    elif value > d_mean and value < d_max:
        value = 75
    elif value == d_mean:
        value = 50
"""

[[[25. 25. 25. 25. 75.]
  [75. 75. 75. 25. 75.]
  [25. 25. 25. 75. 75.]]

 [[75. 75. 75. 75. 75.]
  [75. 75. 25. 25. 25.]
  [25. 75. 25. 25. 75.]]]
100
0


'Method 2\nf = np.where((d > d_min) & (d < d_mean), 25, f)\n\nMethod 3\nf = np.empty(d.shape)\nfor i in range(d.shape[0]):\n    for j in range(d.shape[1]):\n        for k in range(d.shape[2]):\n            if d_min < d[i, j, k] < d_mean:\n                f[i, j, k] = 25\n    elif value > d_mean and value < d_max:\n        value = 75\n    elif value == d_mean:\n        value = 50\n'





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [73]:
### [your code here]
print(d)
print("----------")
print(f)

[[[1.02142715 1.22847828 1.23636085 1.27372269 1.87363296]
  [1.75970565 1.62323311 1.84938767 1.03884973 1.91106535]
  [1.40066535 1.00599448 1.09307211 1.980551   1.8526186 ]]

 [[1.93485536 1.96221093 1.62466333 1.88549352 1.85552566]
  [1.67488414 1.84479562 1.03385445 1.18954918 1.51914385]
  [1.14453054 1.84071941 1.40506194 1.2662533  1.9971622 ]]]
----------
[[[25. 25. 25. 25. 75.]
  [75. 75. 75. 25. 75.]
  [25. 25. 25. 75. 75.]]

 [[75. 75. 75. 75. 75.]
  [75. 75. 25. 25. 25.]
  [25. 75. 25. 25. 75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [78]:
### [your code here]
# Convert f to dtype object to allow string assignment
f = f.astype(object)

for i in range(f.shape[0]):
    for j in range(f.shape[1]):
        for k in range(f.shape[2]):
            if f[i, j, k] == 0:
                f[i, j, k] = "A"
            elif f[i, j, k] == 25:
                f[i, j, k] = "B"
            elif f[i, j, k] == 50:
                f[i, j, k] = "C"
            elif f[i, j, k] == 75:
                f[i, j, k] = "D"
            elif f[i, j, k] == 100:
                f[i, j, k] = "E"

print(f)

[[['B' 'B' 'B' 'B' 'D']
  ['D' 'D' 'D' 'B' 'D']
  ['B' 'B' 'B' 'D' 'D']]

 [['D' 'D' 'D' 'D' 'D']
  ['D' 'D' 'B' 'B' 'B']
  ['B' 'D' 'B' 'B' 'D']]]
